# Generated by Django 3.2.2 on 2022-10-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='complaint.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='complaint.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='subtopic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=100)),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='complaint.question')),
            ],
        ),
    ]
