# Generated by Django 3.2.2 on 2022-10-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20221029_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anyother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
